.TH "D:/Projekte/Projekte_2025/GitHub/FileSortingWizard/FileSortingWiz/obj/Debug Directory Reference" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projekte/Projekte_2025/GitHub/FileSortingWizard/FileSortingWiz/obj/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBnet8\&.0\fP"
.br
.in -1c
