.TH "FileSortingWiz.Rule" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz.Rule \- Represents a set of rules and configurations for managing file paths, metadata, and file-specific rules\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDataBasePath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBDataBaseFileName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBlogFileName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBMediaRootPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBvideoRootPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBimageRootPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBdocumentRootPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBmusicRootPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< String, \fBMetaInfoField\fP > \fBmetaInfoField\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBFileRules\fP > \fBfileRules\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a set of rules and configurations for managing file paths, metadata, and file-specific rules\&. 

This class provides properties to define paths for various media types, a database configuration, and dictionaries for metadata fields and file-specific rules\&. It is designed to centralize and organize file management settings\&.
.PP
Definition at line \fB42\fP of file \fBRuleFile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string FileSortingWiz\&.Rule\&.DataBaseFileName\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB45\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.DataBasePath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB44\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.documentRootPath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB50\fP of file \fBRuleFile\&.cs\fP\&.
.SS "Dictionary<string, \fBFileRules\fP> FileSortingWiz\&.Rule\&.fileRules\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB54\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.imageRootPath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB49\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.logFileName\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB46\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.MediaRootPath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB47\fP of file \fBRuleFile\&.cs\fP\&.
.SS "Dictionary<String, \fBMetaInfoField\fP> FileSortingWiz\&.Rule\&.metaInfoField\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB53\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.musicRootPath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB51\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.Rule\&.videoRootPath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB48\fP of file \fBRuleFile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
