.TH "FileSortingWiz.Wizard" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz.Wizard \- Represents a wizard that processes rule files and manages file data collection\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCollectFileData\fP (string ruleFileName, string inputDirectory, string outputDirectory, bool silent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a wizard that processes rule files and manages file data collection\&. 

The \fBWizard\fP class provides functionality to initialize components and collect file data based on a specified rule file and directory paths\&. It is designed to handle operations related to rule file deserialization and logging\&.
.PP
Definition at line \fB39\fP of file \fBWizard\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FileSortingWiz\&.Wizard\&.CollectFileData (string ruleFileName, string inputDirectory, string outputDirectory, bool silent)"

.PP
Definition at line \fB61\fP of file \fBWizard\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
