.TH "FileSortingWiz.AvailableKeyWords" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz.AvailableKeyWords
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDataType\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBSource\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBValAttribute\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string[] \fBKeyWords\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB63\fP of file \fBRuleFile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string FileSortingWiz\&.AvailableKeyWords\&.DataType\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB65\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string [] FileSortingWiz\&.AvailableKeyWords\&.KeyWords\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB68\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.AvailableKeyWords\&.Source\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB66\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.AvailableKeyWords\&.ValAttribute\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB67\fP of file \fBRuleFile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
