.TH "FileSortingWiz.FileRules" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz.FileRules
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCategory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBRootPath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBSortingPatern\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFileNamePatern\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBRuleFile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string FileSortingWiz\&.FileRules\&.Category\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB73\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.FileRules\&.FileNamePatern\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB76\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.FileRules\&.RootPath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB74\fP of file \fBRuleFile\&.cs\fP\&.
.SS "string FileSortingWiz\&.FileRules\&.SortingPatern\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB75\fP of file \fBRuleFile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
