.TH "FileSortingWiz.MetaInfoField" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz.MetaInfoField
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< String, \fBAvailableKeyWords\fP > \fBavailableKeyWords\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB57\fP of file \fBRuleFile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<String, \fBAvailableKeyWords\fP> FileSortingWiz\&.MetaInfoField\&.availableKeyWords\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB60\fP of file \fBRuleFile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
