.TH "FileSortingWiz.RuleFile" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz.RuleFile \- Represents a file containing rules for organizing and managing files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDeserialize\fP (string ruleFileName)"
.br
.ti -1c
.RI "void \fBSerialize\fP (string ruleFileName)"
.br
.RI "For testing purposes only\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRule\fP \fBrule\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a file containing rules for organizing and managing files\&. 

The \fBRuleFile\fP class provides functionality to deserialize rules from a YAML file and serialize rules for testing purposes\&. It encapsulates a \fBRule\fP object that defines the structure and behavior of the rules\&.
.PP
Definition at line \fB85\fP of file \fBRuleFile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FileSortingWiz\&.RuleFile\&.Deserialize (string ruleFileName)"

.PP
Definition at line \fB89\fP of file \fBRuleFile\&.cs\fP\&.
.SS "void FileSortingWiz\&.RuleFile\&.Serialize (string ruleFileName)"

.PP
For testing purposes only\&. 
.PP
\fBParameters\fP
.RS 4
\fIruleFileName\fP 
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBRuleFile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBRule\fP FileSortingWiz\&.RuleFile\&.rule\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB87\fP of file \fBRuleFile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
