.TH "FileSortingWiz" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSortingWiz
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileMetaInfo\fP"
.br
.ti -1c
.RI "class \fBTSFileWizContext\fP"
.br
.ti -1c
.RI "class \fBDataBase\fP"
.br
.ti -1c
.RI "class \fBLib\fP"
.br
.RI "Provides utility methods for writing messages to a log file, optionally displaying them in the console, and performing string manipulations\&. "
.ti -1c
.RI "class \fBPaternInterpreter\fP"
.br
.ti -1c
.RI "class \fBRule\fP"
.br
.RI "Represents a set of rules and configurations for managing file paths, metadata, and file-specific rules\&. "
.ti -1c
.RI "class \fBMetaInfoField\fP"
.br
.ti -1c
.RI "class \fBAvailableKeyWords\fP"
.br
.ti -1c
.RI "class \fBFileRules\fP"
.br
.ti -1c
.RI "class \fBRuleFile\fP"
.br
.RI "Represents a file containing rules for organizing and managing files\&. "
.ti -1c
.RI "class \fBWizard\fP"
.br
.RI "Represents a wizard that processes rule files and manages file data collection\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
