.TH "D:/Projekte/Projekte_2025/GitHub/FileSortingWizard/FileSortingWiz/obj/Debug/net8.0/FileSortingWiz.AssemblyInfo.cs" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projekte/Projekte_2025/GitHub/FileSortingWizard/FileSortingWiz/obj/Debug/net8.0/FileSortingWiz.AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
