.TH "md__d_1_2_projekte_2_projekte__2025_2_git_hub_2_file_sorting_wizard_2_file_sorting_wizard_2_manual_2index" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d_1_2_projekte_2_projekte__2025_2_git_hub_2_file_sorting_wizard_2_file_sorting_wizard_2_manual_2index \- index 
.PP
/** 
