.TH "D:/Projekte/Projekte_2025/GitHub/FileSortingWizard/FileSortingWiz/Wizard.cs" 3 "Version 0.1.0" "FileSortingWizart" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projekte/Projekte_2025/GitHub/FileSortingWizard/FileSortingWiz/Wizard.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileSortingWiz\&.Wizard\fP"
.br
.RI "Represents a wizard that processes rule files and manages file data collection\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFileSortingWiz\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FileSortingWizart from the source code\&.
